name: deploy
on: 
  push:
    branches:
      - master
jobs:

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:

    - name: checkout
      uses: actions/checkout@v1

    - name: deploy
      uses: actions-hub/gcloud@master
      env:
        PROJECT_ID: gcp-playground-155604
        APPLICATION_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      with:
        args: functions deploy jamie-chicken
